<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme_suggestions_alter
 */
function form_themming_theme_suggestions_alter(array &$suggestions, array $variables) {

    if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
        $original_theme_hook = $variables['theme_hook_original'];

        $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
    }

    return $suggestions;

}

/**
 * Implements hook_form_alter()
 */
function form_themming_form_alter(&$form, FormStateInterface $form_state, $form_id) {

    $view = views_get_current_view();

    if ($form_id == 'search_block_form') {

      $form['#theme'] = ['sepi_search'];

    }
    else if($form_id == 'simplenews_subscriptions_block_035fda10-8cb4-4454-9465-9bd590c3ee3c'){
      $form['#theme'] = ['simplenewssubscription'];
    }
    else if($form_id == 'simplenews_subscriptions_block_a75421c8-cd3a-4dac-9982-2e8dfe7b8443'){
      $form['#theme'] = ['simplenewssubscription2'];
    }
    else if($form_id == 'search_form' ){
      $form['#theme'] = ['search_form'];
      $form['#method'] = 'get';
    }
    else if($view){
      if($view->id() === 'busqueda_de_noticias')
        $form['#theme'] = 'buscador_noticias';
      else if($view->id() === 'licitaciones'){
        $form['#theme'] = 'licitaciones';
      }
      else if($view->id() === 'empresas'){
        $form['#theme'] = 'empresas';
      }
      else if($view->id() === 'privatizaciones' ){
        $form['#theme'] = 'privatizaciones_page';
      }
    }

}

/**
 * Implements hook_theme()
 */
function form_themming_theme() {

    $themes['sepi_search'] = ['render element' => 'form'];
    $themes['simplenewssubscription'] = ['render element' => 'form'];
    $themes['simplenewssubscription2'] = ['render element' => 'form'];
    $themes['buscador_noticias'] = ['render element' => 'form'];
    $themes['licitaciones'] = ['render element' => 'form'];
    $themes['empresas'] = ['render element' => 'form'];
    $themes['privatizaciones'] = ['render element' => 'form'];
    $themes['privatizaciones_page'] = ['render element' => 'form'];
    $themes['search_form'] = ['render element' => 'form'];

    return $themes;

}
